# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - directory: .
    package-ecosystem: gomod
    target-branch: main
    schedule:
      interval: daily
      time: "03:00"
    assignees:
      - a-kataev
