run:
  timeout: 2m
  modules-download-mode: readonly
  go: "1.22"

output:
  formats:
    - format: colored-line-number
  sort-results: true

linters-settings:
  funlen:
    lines: 100
    statements: 50
  varnamelen:
    min-name-length: 2
  exhaustruct:
    exclude:
      - 'net/http\..*'
      - github.com/a-kataev/tg.Chat
  tagliatelle:
    case:
      rules:
        json: snake
  depguard:
    rules:
      main:
        allow:
          - $gostd
          - github.com/a-kataev/tg
          - github.com/stretchr/testify/assert
          - github.com/stretchr/testify/mock

linters:
  fast: false
  disable-all: true
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - containedctx
    - contextcheck
    - copyloopvar
    - cyclop
    ## - deadcode # deprecated
    - decorder
    - depguard
    - dogsled
    - dupl
    - dupword
    - durationcheck
    - errcheck
    - errchkjson
    - errname
    - execinquery
    - exhaustive
    ## - exhaustivestruct # deprecated
    - exhaustruct
    - exportloopref
    - forbidigo
    - forcetypeassert
    - funlen
    - gci
    - ginkgolinter
    - gocheckcompilerdirectives
    - gochecknoglobals
    - gochecknoinits
    - gochecksumtype
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - godox
    - goerr113
    - gofmt
    - gofumpt
    - goheader
    ## - golint # deprecated
    - gomnd
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - gosimple
    - gosmopolitan
    - govet
    - grouper
    ## - ifshort # deprecated
    - inamedparam
    - ineffassign
    - interfacebloat
    ## - interfacer # deprecated
    - intrange
    - ireturn
    - lll
    - loggercheck
    - maintidx
    - makezero
    ## - maligned # deprecated
    - mirror
    - misspell
    - musttag
    - nakedret
    - nestif
    - nilerr
    - nilnil
    - nlreturn
    - noctx
    - nolintlint
    - nonamedreturns
    ## - nosnakecase # deprecated
    - nosprintfhostport
    - perfsprint
    - prealloc
    - predeclared
    - promlinter
    - protogetter
    - reassign
    - revive
    - rowserrcheck
    ## - scopelint # deprecated
    - sloglint
    - spancheck
    - staticcheck
    ## - structcheck # deprecated
    - tagalign
    - tagliatelle
    - tenv
    - thelper
    - tparallel
    - unconvert
    - unparam
    - usestdlibvars
    ## - varcheck # deprecated
    - varnamelen
    - wastedassign
    - whitespace
    - wrapcheck
    - wsl
    - zerologlint
