run:
  timeout: 2m
  modules-download-mode: readonly
  go: 1.21

output:
  format: colored-line-number
  sort-results: true

linters-settings:
  funlen:
    lines: 100
    statements: 50
  varnamelen:
    min-name-length: 2
  cyclop:
    max-complexity: 15
  exhaustruct:
    exclude:
      - 'net/http\..*'
      - github.com/a-kataev/tg.Chat
  wsl:
    allow-assign-and-anything: true
  tagliatelle:
    case:
      rules:
        json: snake
  depguard:
    rules:
      main:
        allow:
          - $gostd
          - github.com/a-kataev/tg
          - github.com/stretchr/testify/assert
          - github.com/stretchr/testify/mock

linters:
  fast: false
  disable-all: true
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - containedctx
    - contextcheck
    - cyclop
    ## - deadcode # deprecated
    - decorder
    - depguard
    - dogsled
    - dupl
    - dupword
    - durationcheck
    - errcheck
    - errchkjson
    - errname
    - errorlint
    - execinquery
    - exhaustive
    ## - exhaustivestruct # deprecated
    - exhaustruct
    - exportloopref
    - forbidigo
    - forcetypeassert
    - funlen
    - gci
    - ginkgolinter
    - gocheckcompilerdirectives
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - godox
    - goerr113
    - gofmt
    - gofumpt
    - goheader
    - goimports
    ## - golint # deprecated
    - gomnd
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - grouper
    ## - ifshort # deprecated
    - importas
    - ineffassign
    - interfacebloat
    ## - interfacer # deprecated
    - ireturn
    - lll
    - loggercheck
    - maintidx
    - makezero
    ## - maligned # deprecated
    - misspell
    - musttag
    - nakedret
    - nestif
    - nilerr
    - nilnil
    - nlreturn
    - noctx
    - nolintlint
    - nonamedreturns
    ## - nosnakecase # deprecated
    - nosprintfhostport
    - paralleltest
    - prealloc
    - predeclared
    - promlinter
    - reassign
    - revive
    - rowserrcheck
    ## - scopelint # deprecated
    - sqlclosecheck
    - staticcheck
    ## - structcheck # deprecated
    - stylecheck
    - tagliatelle
    - tenv
    - testableexamples
    - testpackage
    - thelper
    - tparallel
    - typecheck
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    ## - varcheck # deprecated
    - varnamelen
    - wastedassign
    - whitespace
    - wrapcheck
    - wsl
