project_name: tg
builds:
  - id: tgsend
    main: ./cmd/tgsend
    ldflags:
      - -s -w
    binary: tgsend
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: linux
        goarch: arm64
archives:
  - id: tgsend
    builds:
      - tgsend
    name_template: '{{ .ProjectName }}_v{{ .Version }}_{{ .Os }}_{{ .Arch }}'
    format: tar.gz
    files:
      - xyz*
checksum:
  name_template: '{{ .ProjectName }}_v{{ .Version }}_checksums.txt'
  algorithm: sha256
changelog:
  use: github-native
