name: goreleaser

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  goreleaser:
    name: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.20'
      - uses: goreleaser/goreleaser-action@v1
        with:
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
