name: release

permissions:
  contents: write

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  go-test:
    uses: ./.github/workflows/_go-test.yml
  golangci-lint:
    uses: ./.github/workflows/_golangci-lint.yml
  goreleaser:
    needs:
      - go-test
      - golangci-lint
    uses: ./.github/workflows/_goreleaser.yml
